apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-dbsecret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  rds-host: {{ required "secret.rdsHost is required" .Values.secret.rdsHost }}
  db-name: {{ required "secret.dbName is required" .Values.secret.dbName }}
  db-user: {{ required "secret.dbUser is required" .Values.secret.dbUser }}
  db-password: {{ required "secret.dbPassword is required" .Values.secret.dbPassword }}
